import { readFile } from "node:fs/promises";

type OperationName = "login" | "options" | "createSession" | "keepAlive" | "debug" | "deleteSession" | "healthCheck";

interface OperationLatencySummary {
  p50: number | null;
  p95: number | null;
  samples: number;
}

interface OperationReport {
  name: OperationName;
  attempts: number;
  successes: number;
  failures: number;
  failureReasons: Record<string, number>;
  latency: OperationLatencySummary;
}

interface DebugIndicators {
  attempts: number;
  runtimeMissing: number;
  hasRuntimeFalse: number;
  closedTrue: number;
  attachedSocketsZero: number;
  lastErrorPresent: number;
}

interface LoadTestReport {
  startTime: string;
  endTime: string;
  actualDurationSec: number;
  config: {
    baseUrl: string;
    username: string;
    concurrency: number;
    durationSec: number;
    rampSec: number;
    reportPath?: string;
  };
  operations: OperationReport[];
  debugIndicators: DebugIndicators;
}

interface Thresholds {
  totalFailureRate: number;
  healthFailureRate: number;
  loginP95: number;
  createSessionP95: number;
  keepAliveP95: number;
  debugRuntimeMissing: number;
}

function parseArgs() {
  const raw = process.argv.slice(2);
  if (raw.includes("--help") || raw.includes("-h")) {
    printUsageAndExit(0);
  }
  const getFlag = (key: string): string | undefined => {
    const long = `--${key}`;
    const idx = raw.indexOf(long);
    if (idx >= 0 && idx < raw.length - 1) {
      return raw[idx + 1];
    }
    return undefined;
  };

  const reportPath = getFlag("report") ?? process.env.LOADTEST_REPORT_FILE;
  if (!reportPath) {
    console.error("[loadtest-report] report path is required via --report <file> or LOADTEST_REPORT_FILE.");
    printUsageAndExit(1);
  }

  const thresholds: Thresholds = {
    totalFailureRate: parseFloatFlag("max-total-failure-rate", process.env.LOADTEST_SUMMARY_MAX_FAILURE_RATE, 0.05),
    healthFailureRate: parseFloatFlag("max-health-failure-rate", process.env.LOADTEST_SUMMARY_MAX_HEALTH_FAILURE_RATE, 0.01),
    loginP95: parseFloatFlag("max-login-p95", process.env.LOADTEST_SUMMARY_MAX_LOGIN_P95, 1200),
    createSessionP95: parseFloatFlag("max-create-session-p95", process.env.LOADTEST_SUMMARY_MAX_CREATE_P95, 2000),
    keepAliveP95: parseFloatFlag("max-keepalive-p95", process.env.LOADTEST_SUMMARY_MAX_KEEPALIVE_P95, 1200),
    debugRuntimeMissing: parseFloatFlag("max-debug-runtime-missing", process.env.LOADTEST_SUMMARY_MAX_DEBUG_RUNTIME_MISSING, 0)
  };

  return { reportPath, thresholds };
}

function parseFloatFlag(flagName: string, envValue: string | undefined, fallback: number): number {
  const raw = process.argv.slice(2);
  const long = `--${flagName}`;
  const overrideIndex = raw.indexOf(long);
  if (overrideIndex >= 0 && overrideIndex < raw.length - 1) {
    const parsed = Number(raw[overrideIndex + 1]);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }
  if (envValue) {
    const parsed = Number(envValue);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }
  return fallback;
}

function printUsageAndExit(code: number): never {
  console.error(`Usage: tsx scripts/loadtest-report.ts --report <file>
Options:
  --report <file>                JSON report generated by scripts/loadtest.ts
  --max-total-failure-rate <pct> Allowed total failure rate (default: 0.05)
  --max-health-failure-rate <pct> Allowed health-check failure rate (default: 0.01)
  --max-login-p95 <ms>           P95 latency threshold for login (default: 1200)
  --max-create-session-p95 <ms>  P95 latency threshold for session creation (default: 2000)
  --max-keepalive-p95 <ms>       P95 latency threshold for keepalive (default: 1200)
  --max-debug-runtime-missing <count> Allowed runtime-missing diagnostics (default: 0)
Environment variables prefixed with LOADTEST_SUMMARY_ can override defaults.`);
  process.exit(code);
}

function createCheck(label: string, passed: boolean, detail: string) {
  return { label, passed, detail };
}

async function loadReport(path: string): Promise<string> {
  if (path === "-") {
    return new Promise((resolve, reject) => {
      let data = "";
      process.stdin.setEncoding("utf8");
      process.stdin.on("data", (chunk) => (data += chunk));
      process.stdin.on("end", () => resolve(data));
      process.stdin.on("error", reject);
    });
  }
  return await readFile(path, "utf8");
}

function percent(value: number): string {
  return `${(value * 100).toFixed(2)}%`;
}

async function main(): Promise<void> {
  const { reportPath, thresholds } = parseArgs();
  let raw: string;
  try {
    raw = await loadReport(reportPath);
  } catch (error) {
    console.error(`[loadtest-report] failed to read report: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }

  let report: LoadTestReport;
  try {
    report = JSON.parse(raw) as LoadTestReport;
  } catch (error) {
    console.error(`[loadtest-report] failed to parse report: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }

  const operationsByName = new Map(report.operations.map((op) => [op.name, op]));
  let totalAttempts = 0;
  let totalFailures = 0;
  for (const op of report.operations) {
    totalAttempts += op.attempts;
    totalFailures += op.failures;
  }
  const totalFailureRate = totalAttempts ? totalFailures / totalAttempts : 0;

  const healthOp = operationsByName.get("healthCheck");
  const healthAttempts = healthOp?.attempts ?? 0;
  const healthFailures = healthOp?.failures ?? 0;
  const healthFailureRate = healthAttempts ? healthFailures / healthAttempts : 0;

  const findP95 = (name: OperationName): number | null => operationsByName.get(name)?.latency.p95 ?? null;

  const checks = [] as ReturnType<typeof createCheck>[];
  checks.push(
    createCheck(
      `Overall failure rate ${percent(totalFailureRate)} <= ${percent(thresholds.totalFailureRate)}`,
      totalFailureRate <= thresholds.totalFailureRate,
      `failures ${totalFailures}/${totalAttempts}`
    )
  );
  checks.push(
    createCheck(
      `Health-check failure rate ${percent(healthFailureRate)} <= ${percent(thresholds.healthFailureRate)}`,
      healthFailureRate <= thresholds.healthFailureRate,
      `failures ${healthFailures}/${healthAttempts}`
    )
  );

  const checkLatency = (name: OperationName, max: number | null, label: string) => {
    const p95 = findP95(name);
    if (p95 === null) {
      checks.push(createCheck(`${label} p95`, true, `no samples`));
      return;
    }
    const passed = p95 <= (max ?? Infinity);
    checks.push(createCheck(`${label} p95 ${p95.toFixed(0)}ms <= ${max?.toFixed(0) ?? "n/a"}ms`, passed, `samples ${operationsByName.get(name)?.latency.samples ?? 0}`));
  };

  checkLatency("login", thresholds.loginP95, "login");
  checkLatency("createSession", thresholds.createSessionP95, "create-session");
  checkLatency("keepAlive", thresholds.keepAliveP95, "keepalive");

  const runtimeMissingCount = report.debugIndicators.runtimeMissing;
  checks.push(
    createCheck(
      `Debug runtime missing ${runtimeMissingCount} <= ${thresholds.debugRuntimeMissing}`,
      runtimeMissingCount <= thresholds.debugRuntimeMissing,
      `hasRuntimeFalse ${report.debugIndicators.hasRuntimeFalse}`
    )
  );

  const failedChecks = checks.filter((check) => !check.passed);
  const status = failedChecks.length ? "FAIL" : "PASS";

  console.log(`Report ${reportPath} (${report.startTime} -> ${report.endTime}, ${report.actualDurationSec.toFixed(1)}s) -> ${status}`);
  for (const check of checks) {
    console.log(`${check.passed ? "PASS" : "FAIL"} ${check.label} (${check.detail})`);
  }

  if (failedChecks.length) {
    process.exitCode = 2;
  }
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(`[loadtest-report] unexpected failure: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  });
}
